clear all;
close all;



Fig=figure('Name','Proiect Gac',...
    'Units','normalized',...
    'Position',[0.1 0.2 0.9 0.7],...
    'NumberTitle','off',...
    'color', [0.4660 0.6740 0.1880]);

B_title=uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.2 0.8 0.6 0.05],...
        'Fontname', 'Times New Roman',...
        'Fontsize', 40,...
        'BackgroundColor', [0.4660 0.6740 0.1880],...
        'FontWeight','bold',...
        'String','Tranzistor Bipolar. PSF. Conexiune Baza Comuna');

B_proiect=uicontrol('Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.3 0.6 0.16 0.05],...
        'Fontname', 'Times New Roman',...
        'Fontsize', 16,...
        'backgroundcolor', 'green',...
        'FontWeight','bold',...
        'String','Proiect',...
        'Callback','startproiect');
    
B_prezentare=uicontrol('Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.3 0.5 0.16 0.05],...
        'Fontname', 'Times New Roman',...
        'Fontsize', 16,...
        'backgroundcolor', 'green',...
        'FontWeight','bold',...
        'String','Prezentare',...
        'Callback','open(''PREZENTARE_PR_GAC.pdf'')');



B_documentatie=uicontrol('Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.6 0.6 0.16 0.05],...
        'Fontname', 'Times New Roman',...
        'Fontsize', 16,...
        'backgroundcolor', 'green',...
        'FontWeight','bold',...
        'String','Documentatie',...
        'Callback','open(''DOCUMENTATIE_PR_GAC.pdf'')');

    
B_inchide=uicontrol('Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.6 0.5 0.16 0.05],...
        'Fontname', 'Times New Roman',...
        'Fontsize', 16,...
        'backgroundcolor', 'green',...
        'FontWeight','bold',...
        'String','Inchide',...
        'Callback','close');

