function tranzistor (A,f,N,RB1,RB2,RC,RE,beta,VAl)

Fig=figure( ...
    'Name','Proiect GAC',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.85 0.8],...
    'NumberTitle','off',...
    'color',[0.4660 0.6740 0.1880] ...
    );
    
    VBE=0.7;
    VTh=(RB2./(RB1+RB2))*VAl;
    RTh=(RB1.*RB2)./(RB1+RB2);
    IC=beta*((VTh-VBE)/(RTh+(beta+1)*RE));
    VCE=VAl-IC*(RC+RE);
    
    Ro=RC;
    gm=40.*IC;
    rBE=beta./gm;
    Ri=1./gm;
    Av=gm*RC;
    Ai=1;
   
% ------------------------------------------
   
% buton circuit
B_circuit=uicontrol( ...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.05 0.25 0.15 0.05],...
        'Fontname', 'Times New Roman',...
        'Fontsize', 12,...
        'backgroundcolor', 'green',...
        'String','Circuit initial',...
        'Callback','imshow(imread("circuit_initial.jpeg"))');
    
% buton circuit echivalent in curent continu
B_CC=uicontrol( ...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.05 0.2 0.15 0.05],...
        'Fontname', 'Times New Roman',...
        'Fontsize', 12,...
        'backgroundcolor', 'green',...
        'String','Circuit echivalent in CC',...
        'Callback','imshow(imread("cc.jpeg"))');

 % buton modelul de semnal mic
 B_semnal=uicontrol('Style','pushbutton',...
         'Units','normalized',...
         'Position',[0.05 0.15 0.15 0.05],...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'backgroundcolor', 'green',...
         'String','Modelul de semnal mic',...
         'Callback','imshow(imread("semnal_mic.jpeg"))');
     
 % buton inapoi
 B_inapoi=uicontrol('Style','pushbutton',...
         'Units','normalized',...
         'Position',[0.05 0.075 0.15 0.05],...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'backgroundcolor', 'green',...
         'String','Inapoi',...
         'Callback','close;paginaprincipala;');
     
 % buton inchide
 B_inchide=uicontrol('Style','pushbutton',...
         'Units','normalized',...
         'Position',[0.05 0.025 0.15 0.05],...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'backgroundcolor', 'green',...
         'String','Inchide',...
         'Callback','close;');
     
% --------------------------------------------

 % grup de butoane: parametrii de semnal
 RadioGroup1=uibuttongroup('Visible','on',...
            'Fontname', 'Times New Roman',...
            'Fontsize', 12,...
            'backgroundcolor', 'green',...
            'Title','Parametrii de semnal',...
            'TitlePosition','centertop',...
            'Tag','radiobutton',...
            'Position',[0.05 0.325 0.15 0.15]);
        
 % label : A
 Bt_A=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 12,...
     'Position',[0.055 0.4 0.05 0.025],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','A');

 % input: A
  Be_A=uicontrol('Style','edit',...
     'Units','normalized',...
     'Position',[0.125 0.4 0.05 0.025],...
     'foregroundcolor','k',...
     'String',A,...
     'Callback','A=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
 
 % label: f
 Bt_f=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 12,...
     'Position',[0.055 0.375 0.05 0.025],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','f');
 
 % input: f
  Be_f=uicontrol('Style','edit',...
     'Units','normalized',...
     'Position',[0.125 0.375 0.05 0.025],...
     'foregroundcolor','k',...
     'String',f,...
     'Callback','f=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
     
 % label: N
 Bt_N=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 12,...
     'Position',[0.055 0.35 0.05 0.025],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','N');
 
 % input: N
  Be_N=uicontrol('Style','edit',...
     'Units','normalized',...
     'Position',[0.125 0.35 0.05 0.025],...
     'foregroundcolor','k',...
     'String',N,...
     'Callback','N=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');

% -------------------------------------------------

  % grup de butoane: parametrii de intrare
 RadioGroup2=uibuttongroup('Visible','on',...
            'Fontname', 'Times New Roman',...
            'Fontsize', 12,...
            'backgroundcolor', 'green',...
            'Title','Parametrii de intrare',...
            'TitlePosition','centertop',...
            'Tag','radiobutton',...
            'Position',[0.05 0.75 0.15 0.225]);
        
% label: RB1
 Bt_RB1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 12,...
     'Position',[0.055 0.9 0.05 0.025],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','RB1');
 
% input: RB1
 Be_RB1=uicontrol('Style','edit',...
     'Units','normalized',...
     'Position',[0.125 0.9 0.05 0.025],...
     'foregroundcolor','k',...
     'String',RB1,...
     'Callback','RB1=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
 
% label: RB2
  Bt_RB2=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 12,...
     'Position',[0.055 0.875 0.05 0.025],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','RB2');
 
% input: RB2
  Be_RB2=uicontrol('Style','edit',...
     'Units','normalized',...
     'Position',[0.125 0.875 0.05 0.025],...
     'foregroundcolor','k',...
     'String',RB2,...
     'Callback','RB2=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
 
% label: RC
  Bt_RC=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 12,...
     'Position',[0.055 0.85 0.05 0.025],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','RC');
 
 % input: RC
  Be_RC=uicontrol('Style','edit',...
     'Units','normalized',...
     'Position',[0.125 0.85 0.05 0.025],...
     'foregroundcolor','k',...
     'String',RC,...
     'Callback','RC=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
 

 % label: RE
  Bt_RE=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 12,...
     'Position',[0.055 0.825 0.05 0.025],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','RE');
 
 % input: RE
  Be_RE=uicontrol('Style','edit',...
     'Units','normalized',...
     'Position',[0.125 0.825 0.05 0.025],...
     'foregroundcolor','k',...
     'String',RE,...
     'Callback','RE=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
 
 % label: Beta
  Bt_Beta=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.8 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','Beta');
     
 % input: Beta
  Be_Beta=uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.125 0.8 0.05 0.025],...
        'foregroundcolor','k',...
        'String',beta,...
        'Callback','beta=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
    
 % label: VAl
  Bt_VAl=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.775 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','VAl');
   
 % input: VAl
  Be_VAl=uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.125 0.775 0.05 0.025],...
        'foregroundcolor','k',...
        'String',VAl,...
        'Callback','VAl=str2num(get(gco,''String''));close;tranzistor(A,f,N,RB1,RB2,RC,RE,beta,VAl);');
    
% -----------------------------------------------

% grup butoane: parametrii de iesire
  RadioGroup3=uibuttongroup('Visible','on',...
            'Fontname', 'Times New Roman',...
            'Fontsize', 12,...
            'backgroundcolor', 'green',...
            'Title','Parametrii de iesire',...
            'TitlePosition','centertop',...
            'Tag','radiobutton',...
            'Position',[0.05 0.5 0.15 0.225]);
        
 % label: Ri
  Bt_Ri=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.65 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','Ri');
     
 % output: Ri
  Bt_Ri1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 10,...
     'Position',[0.125 0.65 0.05 0.025],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(Ri));
     
 % label: Ro
  Bt_Ro=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.625 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','Ro');
  
 % output: Ro
  Bt_Ro1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 10,...
     'Position',[0.125 0.625 0.05 0.025],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(Ro));
     
 % label: gm
  Bt_gm=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.6 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','gm');
     
 % output: gm
  Bt_gm1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 10,...
     'Position',[0.125 0.6 0.05 0.025],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(gm));
    
 % label: rBE
  Bt_rBE=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.575 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','rBE');
     
 % output: rBE
  Bt_rBE1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 10,...
     'Position',[0.125 0.575 0.05 0.025],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(rBE));
  
 % label: Av
  Bt_Av=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.55 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','Av');
     
 % output: Av
  Bt_Av1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 10,...
     'Position',[0.125 0.55 0.05 0.025],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(Av));
     
 % label: Ai
  Bt_Ai=uicontrol('Style','text',...
         'Units','normalized',...
         'Fontname', 'Times New Roman',...
         'Fontsize', 12,...
         'Position',[0.055 0.525 0.05 0.025],...
         'backgroundcolor', 'green',...
         'foregroundcolor','black',...
         'String','Ai');
   
  % output: Ai
   Bt_Ri1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 10,...
     'Position',[0.125 0.525 0.05 0.025],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(Ai));
        
% --------------------------------------------

% grup de butoane: PSF
  RadioGroup4=uibuttongroup('Visible','on',...
            'Fontname', 'Times New Roman',...
            'Fontsize', 12,...
            'backgroundcolor', 'green',...
            'Title','PSF',...
            'TitlePosition','centertop',...
            'Tag','radiobutton',...
            'Position',[0.6 0.5 0.375 0.475]);
     
 % label: IC
  Bt_IC=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 24,...
     'Position',[0.625 0.75 0.15 0.05],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','IC');
 
 % output: IC
  Bt_IC1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 20,...
     'Position',[0.8 0.75 0.15 0.05],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(IC));
         
% label: VCE
  Bt_VCE=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 24,...
     'Position',[0.625 0.625 0.15 0.05],...
     'backgroundcolor', 'green',...
     'foregroundcolor','black',...
     'String','VCE');
 
 % output: VCE
   Bt_VCE1=uicontrol('Style','text',...
     'Units','normalized',...
     'Fontname', 'Times New Roman',...
     'Fontsize', 20,...
     'Position',[0.8 0.625 0.15 0.05],...
     'backgroundcolor', 'w',...
     'foregroundcolor','k',...
     'String',num2str(VCE));   

 % --------------------------------------
  T=1./f;
  t=0:T/100:N*T;
  
    % tip = sinus
     vi=A.*sin(2.*pi.*f.*t);
    
     vo=vi*Av;
   
     Ib_values = [0.1 0.2 0.5]; % Exemplu de valori ale curentului de bază
    
     Vt = 0.0259; 

     subplot('position',[0.6 0.025 0.375 0.425]);
     hold on;
     for Ib = Ib_values
         Vce = linspace(0, 5, 100); % Generare de valori pentru tensiunea colector-emitor
         Ic = beta * Ib * (exp(Vce / (beta * Vt)) - 1); % Ecuatia caracteristicii de ieșire
        plot(Vce, Ic, 'DisplayName', ['Ib = ' num2str(Ib) ' mA']);
     end
     xlabel('Vce (V)');
     ylabel('Ic (mA)');
     title('Caracteristica de Ieșire a Tranzistorului Bipolar NPN', 'Color', 'w', 'fontweight','b');
    legend;
    grid on;

     subplot('position',[0.225 0.75 0.35 0.225]);
     plot(t,vi);
     grid on;
     axis on;
     title('Intrare', 'color','w','fontweight','b');
         
     subplot('position',[0.225 0.5 0.35 0.225]);
     plot(t,vo);
     grid on;
     axis on;
     title('Iesire', 'color','w','fontweight','b');
     
  


     subplot('position', [0.225 0.025 0.35 0.425]);
end